# Generated by Django 4.2.14 on 2026-06-19 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=100, unique=True)),
                ('rule_name', models.CharField(max_length=200)),
                ('conditions', models.JSONField(default=dict)),
                ('priority', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'segment_rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='SegmentRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=50)),
                ('value', models.JSONField(default=dict)),
                ('condition_type', models.CharField(choices=[('age', 'Age'), ('gender', 'Gender'), ('city', 'City'), ('country', 'Country'), ('tag', 'Tag'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_rule_conditions', to='core.segmentrule')),
            ],
            options={
                'db_table': 'segment_rule_conditions',
            },
        ),
    ]
